# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - essay-evaluator-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Install npm packages, build then copy files - client
        working-directory: ./client
        run: |
          npm install
          npm run build
          cp -r ./dist ../server/public
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: essay-evaluator-app
          path: server
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: essay-evaluator-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "essay-evaluator-app"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9B2C574260034BD5BFEADF9DBA37A726 }}
          package: .
